export const CREATE_PROJECT_REQUEST = "@CREATEProjectreducer@/CREATE_PROJECT_REQUEST";
export const CREATE_PROJECT_SUCCESS = "@CREATEProjectreducer@/CREATE_PROJECT_SUCCESS";
export const CREATE_PROJECT_FAIL = "@CREATEProjectreducer@/CREATE_PROJECT_FAIL";
